.486
DATA	SEGMENT	USE16
	BUF	DB 'ABC'
	COUNT	EQU	$-BUF			;计算字符串里面的字符个数
	NUM	DB 0H
DATA	ENDS
CODE	SEGMENT	USE16
	ASSUME	CS:CODE,DS:DATA
BEG:
	MOV	AX,	DATA
	MOV	DS,	AX
	MOV BX,	OFFSET	BUF
	MOV AL,	0
	MOV	CX,	COUNT
FIRST:
	CMP	BYTE PTR [BX],	42H
	JC	SECOND
	CMP	BYTE PTR [BX],	45H
	JA	SECOND
	INC AL         ;计算符合要求的字符个数
SECOND:
	INC BX         ;指向下一个字符
	LOOP	FIRST
	MOV CX,	8      ;将数字转换为二进制
	MOV BL,	AL
TRANS:
	MOV	DL, '0'
	ROL	BL,	1
	JNC	PRINT
	MOV	DL,	'1'
PRINT:
	MOV	AH,	2
	INT	21H
	LOOP	TRANS
	MOV	AH,	4CH
	INT 21H
CODE	ENDS
	END	BEG